name: mcp-server
services:
  - name: mcp-service
    environment_slug: python
    source_dir: /
    build_command: pip install -r requirements.txt
    run_command: python server_tool.py
    envs:
      - key: PORT
        scope: RUN_TIME
        value: "9783"
    http_port: 9783
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 5