name: mcp-server
services:
  - name: mcp-service
    environment_slug: python
    source_dir: /
    build_command: pip install -r requirements.txt
    run_command: python server_tool.py
    envs:
      - key: PORT
        scope: RUN_TIME
        value: "8000"
    http_port: 8000